
trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- checkout: self
# Include step to whitelist the secured resources
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sandboxconnection'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'dynamic-whitelisting-scripts/resource_fw/unlock_resource_fw.sh'
    arguments: '-j resources.dev.json -t 5 -r 2'
    workingDirectory: 'dynamic-whitelisting-scripts/resource_fw/'
    failOnStandardError: true
  displayName: Unlock Resource Firewalls

- task: AzureKeyVault@2
  inputs:
    azureSubscription: 'sandboxconnection'
    KeyVaultName: 'elmsandboxakv'
    SecretsFilter: '*'
    RunAsPreJob: false

- task: AzureCLI@2
  inputs:
    azureSubscription: 'sandboxconnection'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: 'dynamic-whitelisting-scripts/resource_fw/lock_resource_fw.sh'
    arguments: '-j resources.dev.json'
    workingDirectory: 'dynamic-whitelisting-scripts/resource_fw/'
  displayName: Lock Resource Firewalls
  condition: always()

